### ISSUE TITLE
for deploy stage

### ISSUE THREAD

**Issue by Nurlan199206** [dtzar/helm-kubectl#37]
Pls you can describe how to use your image for deploy app from docker hub to kubernetes?

i found on some blog... it is right?

```
deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - kubectl config set-cluster k8s --server="${SERVER}"
    - kubectl config set clusters.k8s.certificate-authority-data ${CERTIFICATE_AUTHORITY_DATA}
    - kubectl config set-credentials gitlab --token="${USER_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - sed -i "s/<VERSION>/${CI_COMMIT_SHORT_SHA}/g" deployment.yaml
    - kubectl apply -f deployment.yaml
```
