### ISSUE TITLE
Not able to set Admin default password

### ISSUE THREAD

**Issue by vosuyak** [dtzar/helm-kubectl#66]
Use case:
Looking to use this image in my Kubernetes deployment component and run via kubectl rather than the docker cmd.

The Issue:
When passing the image in my Kubernetes cluster, I'm able to land on the /login page, however, because this is running on Kubernetes and not docker, a generated password is not present on the command prompt.

Potential solution:
Is there a way to pass a temporary default password via, the -e (environment)? With this approach login proceeds to the dashboard.

![image](https://user-images.githubusercontent.com/16410052/95024459-1cc93c80-0651-11eb-8d94-fec93eb76122.png)

**Comment by gabrielcalderon** [comment]
@vosuyak You can do this through your deployment YAML, ex:

```
spec:
  containers:
  - name: envar-demo-container
    image: dtzar/helm-kubectl:latest
    env:
    - name: JENKINS_PASSWORD
      value: "changeme"
```
